# .circleci/config.yaml
version: 2.1 # to enable orb usage, you must be using circleci 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-29

jobs:
  hello_world:
    executor: android
    steps:
      - run: echo "hello world"

workflows:
  every_pull_request:
    jobs: 
      - hello_world
