version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cirlecci/android:api-30

    steps:
      - checkout
      - run: echo "hello world" # execute echo command
